### ISSUE TITLE
Get: base64 decode failed

### ISSUE THREAD

**Issue by mastertinner** [boj/redistore#34] opened 2017-09-04 21:20 UTC
I'm getting the error `securecookie: base64 decode failed - caused by: illegal base64 data at input byte 40` when running the following code:

```go
store, _ := redistore.NewRediStore(10, "tcp", ":6379", "", []byte("secret-key"))
sess, err := store.Get(r, "session-key")
if err != nil {
  panic(err)
}
```

However, if I remove the error checking, everything works fine and the session gets created correctly in Redis. The same seems to happen for `store.New(r, "session-key")`.

I'm using Redis `4.0.1`.

**Comment by edgar-humberto** [comment] 2017-09-05 02:03
it is probably the `-`. Try `session_key`

**Comment by mastertinner** [comment] 2017-09-05 05:56
Thanks for the idea, @edgar-humberto. Replacing the dash with an underscore did not solve my problem. I'm still getting the same error.

**Comment by elithrar** [comment] 2017-09-05 15:45
What version of redistore are you using, @mastertinner - ?

I'm unable to reproduce this with a simple example:

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/boj/redistore"
	"github.com/gorilla/mux"
)

func main() {
	store, err := redistore.NewRediStore(10, "tcp", ":6379", "", []byte("secret-key"))
	if err != nil {
		log.Fatal(err)
	}

	r := mux.NewRouter()
	r.HandleFunc("/get", func(w http.ResponseWriter, r *http.Request) {
		sess, err := store.Get(r, "session-key")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		fmt.Fprintf(w, "%s\n", sess.Values)
	})

	r.HandleFunc("/put/{value}", func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		val, ok := vars["value"]
		if !ok {
			http.Error(w, "no value supplied", http.StatusBadRequest)
			return
		}

		sess, err := store.Get(r, "session-key")
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		sess.Values["value"] = string(val)
		err = sess.Save(r, w)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		fmt.Fprintf(w, "%s\n", sess.Values)
	})

	log.Fatal(http.ListenAndServe("localhost:8000", r))
}
```

**Comment by boj** [comment] 2017-11-28 00:51
Closing since no further feedback came through.

**Closed by boj** 2017-11-28 00:51 UTC
